/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_duowan_sonic_SonicGenerator */

#ifndef _Included_com_duowan_sonic_SonicGenerator
#define _Included_com_duowan_sonic_SonicGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_duowan_sonic_SonicGenerator
 * Method:    getWaveLenByByte
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_duowan_sonic_SonicGenerator_getWaveLenByByte
  (JNIEnv *, jclass);

/*
 * Class:     com_duowan_sonic_SonicGenerator
 * Method:    genWaveData
 * Signature: (Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_duowan_sonic_SonicGenerator_genWaveData
  (JNIEnv *, jclass, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
